export const CONNECTION_STYLE = `
.connection-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:0 0 18px}
.connection-card{display:block;border:1px solid #263958;border-radius:12px;padding:15px 17px;color:#eef5ff;background:#111a2d;text-decoration:none;min-width:0}
.connection-card:hover{border-color:#69b7ff}.connection-card strong{display:block;font-size:17px;margin:6px 0;overflow-wrap:anywhere}.connection-card small{color:#91a5c4;display:block;line-height:1.6}
.connection-card[data-state=good]{border-left:3px solid #6ddd9a}.connection-card[data-state=warn]{border-left:3px solid #ffd27a}.connection-card[data-state=error]{border-left:3px solid #ff8398}
@media(max-width:760px){.connection-grid{grid-template-columns:1fr}}
`;
export const CONNECTION_HTML = `
<section class="connection-grid" aria-label="Connections">
<a class="connection-card" id="connection-copilot" href="/dashboard/setup#copilot"><small>GITHUB COPILOT</small><strong id="copilot-connection-label">Checking sign-in…</strong><small id="copilot-connection-detail">SDK authentication and model access · details →</small></a>
<a class="connection-card" id="connection-codex" href="/dashboard/setup#codex"><small>CODEX</small><strong id="codex-connection-label">Checking configuration…</strong><small id="codex-connection-detail">Configuration and observed traffic · details →</small></a>
<a class="connection-card" id="connection-restore" href="/dashboard/setup#restore"><small>RESTORE & SETUP</small><strong id="restore-connection-label">Checking backup…</strong><small id="connection-checked">Unmodified Codex · reversible provider configuration</small></a>
</section>`;
export const CONNECTION_SCRIPT = `
(function(){
const labels={ready:'Connected · models available','no-models':'Signed in · no GPT access','sign-in':'Sign-in required',unavailable:'Check unavailable',unknown:'Check unavailable','not-found':'Installation not found','not-configured':'Not configured','relay-offline':'Configured · relay offline',configured:'Configured · awaiting traffic','traffic-observed':'Recent Codex traffic'};
const text=(id,value)=>{const node=document.getElementById(id);if(node)node.textContent=value;};
let inFlight=false;
async function check(){if(inFlight)return;inFlight=true;try{
const response=await fetch('/dashboard/setup/status',{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();
text('copilot-connection-label',labels[data.states.copilot]||'Unknown');
text('codex-connection-label',labels[data.states.codex]||'Unknown');
text('copilot-connection-detail',data.dependencies?(data.copilot.models||[]).length+' available GPT models · inspect setup →':'Install dependencies using the setup guide →');
text('codex-connection-detail',data.states.lastSeenAt?'Last request '+new Date(data.states.lastSeenAt).toLocaleTimeString()+' · observed, not a persistent connection':'Reopen a Codex task and send a prompt to verify routing →');
text('restore-connection-label',({verified:'Original config protected',invalid:'Backup needs attention','not-created':'Ready for first setup'})[data.installation.backup]||'Backup not verified');
text('connection-checked','Checked '+new Date(data.sampledAt).toLocaleTimeString()+' · status cache up to 30 seconds');
for(const name of ['copilot','codex']){const node=document.getElementById('connection-'+name);if(node)node.dataset.state=['ready','traffic-observed'].includes(data.states[name])?'good':'warn';}
const restore=document.getElementById('connection-restore');if(restore)restore.dataset.state=data.installation.backup==='verified'?'good':data.installation.backup==='invalid'?'error':'warn';
text('setup-relay-state',data.relay?.ok?'Relay running · v'+data.relay.version+' · '+data.relay.model:'Relay is not ready yet. Follow the steps below.');
text('setup-models',(data.copilot.models||[]).join(', ')||'Models appear after sign-in.');
text('setup-config-state',data.installation.customHome?'Using your CODEX_HOME override.':'Using the current user’s .codex directory.');
}catch{text('copilot-connection-label','Status unavailable');text('codex-connection-label','Status unavailable');text('connection-checked','Run npm run setup to open diagnostics.');}finally{inFlight=false;}}
check();setInterval(()=>{if(!document.hidden)check();},5000);
})();`;

export const SETUP_HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connect · Codex Copilot Relay</title><link rel="icon" href="data:,">
<style>*{box-sizing:border-box}body{margin:0;background:#080d19;color:#eef5ff;font:15px/1.6 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:36px 22px 70px}h1{font-size:32px;letter-spacing:-.035em;margin:0}h2{font-size:20px;margin:0 0 10px}p{margin:8px 0 18px;color:#a8b8d0}a{color:#8bc8ff}code{overflow-wrap:anywhere;color:#b9e8db}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#080d19;padding:14px;border-radius:8px}article{background:#111a2d;border:1px solid #263958;padding:22px;border-radius:14px;margin:14px 0;scroll-margin-top:16px}.tag{font-size:12px;color:#69b7ff;text-transform:uppercase;letter-spacing:.12em}.primary{display:inline-block;background:#203c61;border:1px solid #4274ac;border-radius:8px;padding:10px 16px;color:#fff;text-decoration:none}.note{border-left:3px solid #ffd27a;padding-left:15px}.row{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:24px;flex-wrap:wrap}button{font:inherit;color:#fff;background:#203c61;border:1px solid #4274ac;padding:8px 14px;border-radius:8px;cursor:pointer}.models{font-size:12px;overflow-wrap:anywhere}${CONNECTION_STYLE}</style></head><body><main>
<div class="row"><div><div class="tag">Codex Copilot Relay · connection center</div><h1>Your subscription. Your workspace.</h1><p>GitHub Copilot inference in stock Codex. No patched app, no account-token copying.</p></div><a class="primary" href="__DASHBOARD_URL__">Open dashboard →</a></div>
${CONNECTION_HTML}
<p id="setup-relay-state" role="status">Checking the relay…</p>
<article id="start"><div class="tag">01 · Start here</div><h2>Open setup before connecting</h2><p>Extract the repository to a folder you own. In that folder, open a terminal and run the command below. Keep it open during setup. This connection center runs even before the relay dependencies are installed or GitHub is signed in.</p>
<pre>npm run setup</pre><p class="note">This release provides guided, read-only setup—not a one-click installer. Click a status card to see its fix, then run the shown commands locally. Nothing on this page installs software or changes configuration.</p>
<p>First install <a href="https://nodejs.org/en/download" target="_blank" rel="noopener noreferrer">Node.js 22 LTS or newer</a>. Then install pinned dependencies in the repository folder:</p><pre>npm ci</pre><p>Do not reinstall dependencies while the relay is running. No global Copilot CLI install is required; the pinned dependency includes it.</p></article>
<article id="copilot"><div class="tag">02 · GitHub Copilot</div><h2>Sign in with GitHub</h2><p>Run the official Copilot CLI login command below and complete its browser/device authorization. The connection center then checks accessible models. A GitHub login alone does not guarantee model access: your Copilot plan, usage and organization policy still apply.</p><pre>node node_modules/@github/copilot/npm-loader.js login</pre><p>We never ask for your GitHub password or copy credentials into the relay. Finish active relay tasks before changing the GitHub login.</p><p><a href="https://docs.github.com/en/copilot/how-tos/set-up/install-copilot-cli" target="_blank" rel="noopener noreferrer">Official Copilot CLI setup</a> · <a href="https://github.com/settings/copilot" target="_blank" rel="noopener noreferrer">Copilot account settings</a></p><div class="models" id="setup-models"></div></article>
<article id="codex"><div class="tag">03 · Stock Codex</div><h2>Connect, then verify a real request</h2><p>Install and open the <a href="https://developers.openai.com/codex/app/" target="_blank" rel="noopener noreferrer">official Codex app</a>. Select a model listed above, then run the existing repair command below (replace the model ID if needed). It backs up the config, changes managed provider settings, creates recovery shortcuts, and opens the dashboard.</p><pre>powershell -NoProfile -ExecutionPolicy Bypass -File .\Repair-Codex-CopilotProxy.ps1 -Model gpt-6-astra</pre><p id="setup-config-state"></p><p>After connecting, reopen the task and send a short prompt. <strong>Configured</strong> means the TOML points here; <strong>Recent Codex traffic</strong> means this relay observed a Codex-labelled request within two minutes. Check its completed result in request history to verify inference.</p><p>Need to retry? Use <code>Start or Repair Codex Copilot Bridge</code> on your desktop. Active exchanges defer runtime updates instead of being killed.</p></article>
<article id="restore"><div class="tag">04 · Your exit path</div><h2>Restore Normal Codex</h2><p>Use the desktop <code>Restore Normal Codex (Disable Copilot Bridge)</code> shortcut. It stops relay recovery and restores the SHA-256-verified original TOML. Reopen Codex afterward. Your account, pairings and installed engine are not replaced.</p><p class="note">A full restore returns to the saved original config. Review unrelated TOML changes made after that backup. If the backup is invalid, do not delete it or overwrite it—repair the backup first.</p></article>
<article><div class="tag">Scope & limits</div><h2>Clear boundaries, no hidden fallback</h2><p>Guided setup and lifecycle controls target Windows 11. Manual Responses use on other systems is documented separately. Copilot runs supported inference; Codex owns tools, files, approvals and memory. Optional native image generation consumes separate OpenAI allowance and requires explicit opt-in. Native OpenAI search is removed.</p><p>Native app voice is unsupported with this provider in the tested stock engine. We do not patch Codex to add it. No 12-hour soak or phone-to-host round trip is implied by the setup checks.</p><a href="https://github.com/madhavsomani/codex-copilot-relay" target="_blank" rel="noopener noreferrer">Repository & complete setup guide</a></article>
<p>Created by <a href="https://www.linkedin.com/in/madhavsomani" target="_blank" rel="noopener noreferrer">Madhav Somani</a> · Unofficial compatibility relay · loopback only</p>
</main><script>${CONNECTION_SCRIPT}</script></body></html>`;
